name: Stephen Koren
description: Game Programmer

avatar: https://avatars1.githubusercontent.com/u/10856992
timezone: Australia/Sydney

footer-links:
  dribbble:
  email: stephenkoren7@gmail.com
  facebook:
  flickr:
  github: 3pills
  instagram:
  linkedin: stephenkoren
  pinterest:
  rss:
  twitter: stephenkoren7
  stackoverflow:
  youtube: channel/UCVn2zVEofBtpqMn4meyBKTQ
  googleplus:

collections:
  projects:
    output: true
    permalink: /projects/:path/

disqus: stephenkorengameprogrammer

google_analytics: UA-63619308-1

url: http://www.stephenkoren.net/
baseurl: ""

permalink: /blogs/:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

version: v1.1.0

cleancategories:
  earthscape: EarthScape
  general: General
  webgame: Web-based Game
  researchblog: Market Research

sass:
  style: :expanded

gems:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME