#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Stephen Koren

# Short bio or description (displayed in the header)
description: Game Programmer

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars1.githubusercontent.com/u/10856992

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: stephenkoren7@gmail.com
  facebook:
  flickr:
  github: 3pills
  instagram:
  linkedin: stephenkoren
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: stephenkoren7
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: channel/UCVn2zVEofBtpqMn4meyBKTQ
  googleplus: # anything in your profile username that comes after plus.google.com/

collections:
  projects:
    output: true
    permalink: /projects/:path/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: stephenkorengameprogrammer

google_analytics: UA-63619308-1

url: http://3pills.github.io/
baseurl: ""

permalink: /blogs/:categories/:title/

markdown: kramdown
highlighter: rouge

# The release of Jekyll Now that you're using
version: v1.1.0

cleancategories:
  earthscape: EarthScape
  general: General
  webgame: Web-based Game

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME