name: Stephen Koren
description: Game Programmer

avatar: https://avatars1.githubusercontent.com/u/10856992
timezone: Australia/Sydney

footer-links:
  dribbble:
  email: stephenkoren7@gmail.com
  facebook:
  flickr:
  github: 
  instagram:
  linkedin: stephenkoren
  pinterest:
  rss:
  twitter: stephenkoren7
  stackoverflow:
  youtube: channel/UCVn2zVEofBtpqMn4meyBKTQ
  googleplus:

collections:
  projects:
    output: true
    permalink: /projects/:path/

disqus: stephenkorengameprogrammer

google_analytics: UA-63619308-1

url: http://www.stephenkoren.net/
baseurl: ""

permalink: /blogs/:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

version: v1.1.0

cleancategories:
  earthscape: EarthScape
  general: General
  webgame: Web-based Game
  cardboard_vr: Cardboard VR
  neural_research: Neural Research 

categorydesc:
  earthscape: Blog for a student group project I was a part of in the first year of my programming degree.
  general: Blog posts on the status of myself and the website as a whole.
  webgame: Blog for a HTML5 and JavaScript based game which I started during the third year of my programming degree.
  cardboard_vr: Blog for a Virtual Reality game which I started during the third year of my programming degree.
  neural_research: Blog for research and development into applying the field of neural networks to independently play Quake.

sass:
  style: :expanded

gems:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME